Expose resourceLimits for instances of pods and apps
mesosphere/marathon pull request #7185
Opened 2020-05-20 00:14 UTC by timcharper

JIRA Issues: MARATHON-8749

2020-07-27 13:19 UTC, deveshk0 commented
any idea when it will available?

2020-10-22 15:25 UTC, timcharper commented
Planning on merging this for DC/OS 2.2

2020-10-26 10:55 UTC, pierrebeitz requested changes
I think we should not pursue implementing this if we don't want to factor in exector-resources and number of instances, as else it does not help clients much with that calculations.

I apologize for not properly articulating this in the first place.

2020-10-26 10:55 UTC, pierrebeitz commented on src/main/scala/mesosphere/marathon/core/pod/PodDefinition.scala
> +    }
only now i realize that this won't help the frontend much.  
i was looking to have marathon factor in the number of currently running instances as well as the executor needs.

here are the current calculations: https://github.com/dcos/dcos-ui/blob/69d94db858d6c406c43846db586b57ca09100de1/plugins/services/src/js/columns/resourceLimits.ts#L34

i also think that we should make a difference between `None` and `0` as we recently encountered quota issues due to exactly not making that difference: https://jira.d2iq.com/browse/COPS-6589.

2020-10-26 15:16 UTC, closed without merging